swagger: '2.0'
info:
  version: 0.0.1
  title: 'Esercizio Botanica'
  description: 'API per gestire un blog di botanica'
host: botanica.swagger.io
schemes:
  - http
  - https

paths:
  /articoli/:
    get:
      summary: "Ottenere l'elenco di tutti gli articoli."
      operationId: "listaArticoli"
      parameters:
        - name: mindata
          in: query
          description: "minimum data degli articoli"
          type: string
          required: true
        - name: categoria
          in: query
          description: "Categoria degli articoli"
          type: string
          required: true
          enum:
            - "orto"
            - "fiori"
            - "attrezzi"
            - "prodotti"
            - "consigli"
            - "news"
      responses:
        200:
          description: 'successo'
          schema:
            type: array
            items:
              $ref: '#/definitions/Articolo'
        400:
          description: 'Errore richiesta'
    post:
      summary: 'Aggiungere un nuovo articolo'
      operationId: 'aggiungiArticolo'
      parameters:
        - name: articolo
          in: body
          description: 'articolo da aggiungere'
          required: true
          schema:
            $ref: '#/definitions/Articolo'
      responses:
        200:
          description: 'succeso'
        400:
          description: "errore richiesta"
  /articoli/{articoloID}:
    put:
      summary: 'aggiornare un articolo'
      operationId: 'aggiornaArticolo'
      parameters:
        - name: articoloID
          description: 'articolo da aggiornare'
          type: integer
          in: path
          required: true
        - name: articolo
          in: body
          description: "articolo con il contenuto aggiornato"
          required: true
          schema:
            $ref: "#/definitions/Articolo"
      responses:
        200:
          description: 'successo - articolo aggiornato'
        400:
          description: 'errore, ID non valido'

definitions:
  Articolo:
    type: object
    required:
      - id
      - data
      - titolo
      - categoria
      - contenuto
    properties:
      id:
        type: integer
        minimum: 0
      data:
        type: string
        example: '06/03/2022'
      titolo:
        type: string
        example: 'Le fiori invernali'
      contenuto:
        type: string
        example: "L'inverno ci porta delle fiori belle..."
      categoria:
        type: array
        items:
          type: "string"
          enum:
            - "orto"
            - "fiori"
            - "attrezzi"
            - "prodotti"
            - "consigli"
            - "news"